#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qlthuvien")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTheloaisach(Theloaisach instance);
    partial void UpdateTheloaisach(Theloaisach instance);
    partial void DeleteTheloaisach(Theloaisach instance);
    partial void InsertPhieumuonsach(Phieumuonsach instance);
    partial void UpdatePhieumuonsach(Phieumuonsach instance);
    partial void DeletePhieumuonsach(Phieumuonsach instance);
    partial void InsertPhieuphat(Phieuphat instance);
    partial void UpdatePhieuphat(Phieuphat instance);
    partial void DeletePhieuphat(Phieuphat instance);
    partial void InsertSach_Theloaisach(Sach_Theloaisach instance);
    partial void UpdateSach_Theloaisach(Sach_Theloaisach instance);
    partial void DeleteSach_Theloaisach(Sach_Theloaisach instance);
    partial void InsertThedocgia(Thedocgia instance);
    partial void UpdateThedocgia(Thedocgia instance);
    partial void DeleteThedocgia(Thedocgia instance);
    partial void InsertDocgia(Docgia instance);
    partial void UpdateDocgia(Docgia instance);
    partial void DeleteDocgia(Docgia instance);
    partial void InsertSach(Sach instance);
    partial void UpdateSach(Sach instance);
    partial void DeleteSach(Sach instance);
    partial void InsertPhieumuonsach_sach(Phieumuonsach_sach instance);
    partial void UpdatePhieumuonsach_sach(Phieumuonsach_sach instance);
    partial void DeletePhieumuonsach_sach(Phieumuonsach_sach instance);
    partial void InsertNhanvien(Nhanvien instance);
    partial void UpdateNhanvien(Nhanvien instance);
    partial void DeleteNhanvien(Nhanvien instance);
    partial void InsertTaikhoan(Taikhoan instance);
    partial void UpdateTaikhoan(Taikhoan instance);
    partial void DeleteTaikhoan(Taikhoan instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::Login.Properties.Settings.Default.qlthuvienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Theloaisach> Theloaisaches
		{
			get
			{
				return this.GetTable<Theloaisach>();
			}
		}
		
		public System.Data.Linq.Table<Phieumuonsach> Phieumuonsaches
		{
			get
			{
				return this.GetTable<Phieumuonsach>();
			}
		}
		
		public System.Data.Linq.Table<Phieuphat> Phieuphats
		{
			get
			{
				return this.GetTable<Phieuphat>();
			}
		}
		
		public System.Data.Linq.Table<Sach_Theloaisach> Sach_Theloaisaches
		{
			get
			{
				return this.GetTable<Sach_Theloaisach>();
			}
		}
		
		public System.Data.Linq.Table<Thedocgia> Thedocgias
		{
			get
			{
				return this.GetTable<Thedocgia>();
			}
		}
		
		public System.Data.Linq.Table<Docgia> Docgias
		{
			get
			{
				return this.GetTable<Docgia>();
			}
		}
		
		public System.Data.Linq.Table<Sach> Saches
		{
			get
			{
				return this.GetTable<Sach>();
			}
		}
		
		public System.Data.Linq.Table<Phieumuonsach_sach> Phieumuonsach_saches
		{
			get
			{
				return this.GetTable<Phieumuonsach_sach>();
			}
		}
		
		public System.Data.Linq.Table<Nhanvien> Nhanviens
		{
			get
			{
				return this.GetTable<Nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<Taikhoan> Taikhoans
		{
			get
			{
				return this.GetTable<Taikhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Theloaisach")]
	public partial class Theloaisach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Matheloai;
		
		private string _Tentheloai;
		
		private EntitySet<Sach_Theloaisach> _Sach_Theloaisaches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatheloaiChanging(int value);
    partial void OnMatheloaiChanged();
    partial void OnTentheloaiChanging(string value);
    partial void OnTentheloaiChanged();
    #endregion
		
		public Theloaisach()
		{
			this._Sach_Theloaisaches = new EntitySet<Sach_Theloaisach>(new Action<Sach_Theloaisach>(this.attach_Sach_Theloaisaches), new Action<Sach_Theloaisach>(this.detach_Sach_Theloaisaches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matheloai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Matheloai
		{
			get
			{
				return this._Matheloai;
			}
			set
			{
				if ((this._Matheloai != value))
				{
					this.OnMatheloaiChanging(value);
					this.SendPropertyChanging();
					this._Matheloai = value;
					this.SendPropertyChanged("Matheloai");
					this.OnMatheloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tentheloai", DbType="NVarChar(100)")]
		public string Tentheloai
		{
			get
			{
				return this._Tentheloai;
			}
			set
			{
				if ((this._Tentheloai != value))
				{
					this.OnTentheloaiChanging(value);
					this.SendPropertyChanging();
					this._Tentheloai = value;
					this.SendPropertyChanged("Tentheloai");
					this.OnTentheloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Theloaisach_Sach_Theloaisach", Storage="_Sach_Theloaisaches", ThisKey="Matheloai", OtherKey="Matheloai")]
		public EntitySet<Sach_Theloaisach> Sach_Theloaisaches
		{
			get
			{
				return this._Sach_Theloaisaches;
			}
			set
			{
				this._Sach_Theloaisaches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sach_Theloaisaches(Sach_Theloaisach entity)
		{
			this.SendPropertyChanging();
			entity.Theloaisach = this;
		}
		
		private void detach_Sach_Theloaisaches(Sach_Theloaisach entity)
		{
			this.SendPropertyChanging();
			entity.Theloaisach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phieumuonsach")]
	public partial class Phieumuonsach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Maphieumuon;
		
		private System.Nullable<System.DateTime> _Ngaymuon;
		
		private System.Nullable<System.DateTime> _Ngayhethan;
		
		private System.Nullable<System.DateTime> _Ngaytra;
		
		private System.Nullable<bool> _Trangthai;
		
		private System.Nullable<int> _Mathedocgia;
		
		private System.Nullable<int> _Maphieuphat;
		
		private EntitySet<Phieumuonsach_sach> _Phieumuonsach_saches;
		
		private EntityRef<Phieuphat> _Phieuphat;
		
		private EntityRef<Thedocgia> _Thedocgia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaphieumuonChanging(int value);
    partial void OnMaphieumuonChanged();
    partial void OnNgaymuonChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaymuonChanged();
    partial void OnNgayhethanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayhethanChanged();
    partial void OnNgaytraChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaytraChanged();
    partial void OnTrangthaiChanging(System.Nullable<bool> value);
    partial void OnTrangthaiChanged();
    partial void OnMathedocgiaChanging(System.Nullable<int> value);
    partial void OnMathedocgiaChanged();
    partial void OnMaphieuphatChanging(System.Nullable<int> value);
    partial void OnMaphieuphatChanged();
    #endregion
		
		public Phieumuonsach()
		{
			this._Phieumuonsach_saches = new EntitySet<Phieumuonsach_sach>(new Action<Phieumuonsach_sach>(this.attach_Phieumuonsach_saches), new Action<Phieumuonsach_sach>(this.detach_Phieumuonsach_saches));
			this._Phieuphat = default(EntityRef<Phieuphat>);
			this._Thedocgia = default(EntityRef<Thedocgia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maphieumuon", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Maphieumuon
		{
			get
			{
				return this._Maphieumuon;
			}
			set
			{
				if ((this._Maphieumuon != value))
				{
					this.OnMaphieumuonChanging(value);
					this.SendPropertyChanging();
					this._Maphieumuon = value;
					this.SendPropertyChanged("Maphieumuon");
					this.OnMaphieumuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaymuon", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaymuon
		{
			get
			{
				return this._Ngaymuon;
			}
			set
			{
				if ((this._Ngaymuon != value))
				{
					this.OnNgaymuonChanging(value);
					this.SendPropertyChanging();
					this._Ngaymuon = value;
					this.SendPropertyChanged("Ngaymuon");
					this.OnNgaymuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayhethan", DbType="Date")]
		public System.Nullable<System.DateTime> Ngayhethan
		{
			get
			{
				return this._Ngayhethan;
			}
			set
			{
				if ((this._Ngayhethan != value))
				{
					this.OnNgayhethanChanging(value);
					this.SendPropertyChanging();
					this._Ngayhethan = value;
					this.SendPropertyChanged("Ngayhethan");
					this.OnNgayhethanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaytra", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaytra
		{
			get
			{
				return this._Ngaytra;
			}
			set
			{
				if ((this._Ngaytra != value))
				{
					this.OnNgaytraChanging(value);
					this.SendPropertyChanging();
					this._Ngaytra = value;
					this.SendPropertyChanged("Ngaytra");
					this.OnNgaytraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="Bit")]
		public System.Nullable<bool> Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this.OnTrangthaiChanging(value);
					this.SendPropertyChanging();
					this._Trangthai = value;
					this.SendPropertyChanged("Trangthai");
					this.OnTrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mathedocgia", DbType="Int")]
		public System.Nullable<int> Mathedocgia
		{
			get
			{
				return this._Mathedocgia;
			}
			set
			{
				if ((this._Mathedocgia != value))
				{
					if (this._Thedocgia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMathedocgiaChanging(value);
					this.SendPropertyChanging();
					this._Mathedocgia = value;
					this.SendPropertyChanged("Mathedocgia");
					this.OnMathedocgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maphieuphat", DbType="Int")]
		public System.Nullable<int> Maphieuphat
		{
			get
			{
				return this._Maphieuphat;
			}
			set
			{
				if ((this._Maphieuphat != value))
				{
					if (this._Phieuphat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaphieuphatChanging(value);
					this.SendPropertyChanging();
					this._Maphieuphat = value;
					this.SendPropertyChanged("Maphieuphat");
					this.OnMaphieuphatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phieumuonsach_Phieumuonsach_sach", Storage="_Phieumuonsach_saches", ThisKey="Maphieumuon", OtherKey="Maphieumuon")]
		public EntitySet<Phieumuonsach_sach> Phieumuonsach_saches
		{
			get
			{
				return this._Phieumuonsach_saches;
			}
			set
			{
				this._Phieumuonsach_saches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phieuphat_Phieumuonsach", Storage="_Phieuphat", ThisKey="Maphieuphat", OtherKey="Maphieuphat", IsForeignKey=true)]
		public Phieuphat Phieuphat
		{
			get
			{
				return this._Phieuphat.Entity;
			}
			set
			{
				Phieuphat previousValue = this._Phieuphat.Entity;
				if (((previousValue != value) 
							|| (this._Phieuphat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phieuphat.Entity = null;
						previousValue.Phieumuonsaches.Remove(this);
					}
					this._Phieuphat.Entity = value;
					if ((value != null))
					{
						value.Phieumuonsaches.Add(this);
						this._Maphieuphat = value.Maphieuphat;
					}
					else
					{
						this._Maphieuphat = default(Nullable<int>);
					}
					this.SendPropertyChanged("Phieuphat");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thedocgia_Phieumuonsach", Storage="_Thedocgia", ThisKey="Mathedocgia", OtherKey="Mathedocgia", IsForeignKey=true)]
		public Thedocgia Thedocgia
		{
			get
			{
				return this._Thedocgia.Entity;
			}
			set
			{
				Thedocgia previousValue = this._Thedocgia.Entity;
				if (((previousValue != value) 
							|| (this._Thedocgia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thedocgia.Entity = null;
						previousValue.Phieumuonsaches.Remove(this);
					}
					this._Thedocgia.Entity = value;
					if ((value != null))
					{
						value.Phieumuonsaches.Add(this);
						this._Mathedocgia = value.Mathedocgia;
					}
					else
					{
						this._Mathedocgia = default(Nullable<int>);
					}
					this.SendPropertyChanged("Thedocgia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phieumuonsach_saches(Phieumuonsach_sach entity)
		{
			this.SendPropertyChanging();
			entity.Phieumuonsach = this;
		}
		
		private void detach_Phieumuonsach_saches(Phieumuonsach_sach entity)
		{
			this.SendPropertyChanging();
			entity.Phieumuonsach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phieuphat")]
	public partial class Phieuphat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Maphieuphat;
		
		private System.Nullable<int> _Sotienphat;
		
		private string _Ghichu;
		
		private EntitySet<Phieumuonsach> _Phieumuonsaches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaphieuphatChanging(int value);
    partial void OnMaphieuphatChanged();
    partial void OnSotienphatChanging(System.Nullable<int> value);
    partial void OnSotienphatChanged();
    partial void OnGhichuChanging(string value);
    partial void OnGhichuChanged();
    #endregion
		
		public Phieuphat()
		{
			this._Phieumuonsaches = new EntitySet<Phieumuonsach>(new Action<Phieumuonsach>(this.attach_Phieumuonsaches), new Action<Phieumuonsach>(this.detach_Phieumuonsaches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maphieuphat", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Maphieuphat
		{
			get
			{
				return this._Maphieuphat;
			}
			set
			{
				if ((this._Maphieuphat != value))
				{
					this.OnMaphieuphatChanging(value);
					this.SendPropertyChanging();
					this._Maphieuphat = value;
					this.SendPropertyChanged("Maphieuphat");
					this.OnMaphieuphatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sotienphat", DbType="Int")]
		public System.Nullable<int> Sotienphat
		{
			get
			{
				return this._Sotienphat;
			}
			set
			{
				if ((this._Sotienphat != value))
				{
					this.OnSotienphatChanging(value);
					this.SendPropertyChanging();
					this._Sotienphat = value;
					this.SendPropertyChanged("Sotienphat");
					this.OnSotienphatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghichu", DbType="NVarChar(200)")]
		public string Ghichu
		{
			get
			{
				return this._Ghichu;
			}
			set
			{
				if ((this._Ghichu != value))
				{
					this.OnGhichuChanging(value);
					this.SendPropertyChanging();
					this._Ghichu = value;
					this.SendPropertyChanged("Ghichu");
					this.OnGhichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phieuphat_Phieumuonsach", Storage="_Phieumuonsaches", ThisKey="Maphieuphat", OtherKey="Maphieuphat")]
		public EntitySet<Phieumuonsach> Phieumuonsaches
		{
			get
			{
				return this._Phieumuonsaches;
			}
			set
			{
				this._Phieumuonsaches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phieumuonsaches(Phieumuonsach entity)
		{
			this.SendPropertyChanging();
			entity.Phieuphat = this;
		}
		
		private void detach_Phieumuonsaches(Phieumuonsach entity)
		{
			this.SendPropertyChanging();
			entity.Phieuphat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sach_Theloaisach")]
	public partial class Sach_Theloaisach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _Masach;
		
		private System.Nullable<int> _Matheloai;
		
		private int _ids_tl;
		
		private EntityRef<Theloaisach> _Theloaisach;
		
		private EntityRef<Sach> _Sach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMasachChanging(System.Nullable<int> value);
    partial void OnMasachChanged();
    partial void OnMatheloaiChanging(System.Nullable<int> value);
    partial void OnMatheloaiChanged();
    partial void Onids_tlChanging(int value);
    partial void Onids_tlChanged();
    #endregion
		
		public Sach_Theloaisach()
		{
			this._Theloaisach = default(EntityRef<Theloaisach>);
			this._Sach = default(EntityRef<Sach>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Masach", DbType="Int")]
		public System.Nullable<int> Masach
		{
			get
			{
				return this._Masach;
			}
			set
			{
				if ((this._Masach != value))
				{
					if (this._Sach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMasachChanging(value);
					this.SendPropertyChanging();
					this._Masach = value;
					this.SendPropertyChanged("Masach");
					this.OnMasachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matheloai", DbType="Int")]
		public System.Nullable<int> Matheloai
		{
			get
			{
				return this._Matheloai;
			}
			set
			{
				if ((this._Matheloai != value))
				{
					if (this._Theloaisach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatheloaiChanging(value);
					this.SendPropertyChanging();
					this._Matheloai = value;
					this.SendPropertyChanged("Matheloai");
					this.OnMatheloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ids_tl", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ids_tl
		{
			get
			{
				return this._ids_tl;
			}
			set
			{
				if ((this._ids_tl != value))
				{
					this.Onids_tlChanging(value);
					this.SendPropertyChanging();
					this._ids_tl = value;
					this.SendPropertyChanged("ids_tl");
					this.Onids_tlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Theloaisach_Sach_Theloaisach", Storage="_Theloaisach", ThisKey="Matheloai", OtherKey="Matheloai", IsForeignKey=true)]
		public Theloaisach Theloaisach
		{
			get
			{
				return this._Theloaisach.Entity;
			}
			set
			{
				Theloaisach previousValue = this._Theloaisach.Entity;
				if (((previousValue != value) 
							|| (this._Theloaisach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Theloaisach.Entity = null;
						previousValue.Sach_Theloaisaches.Remove(this);
					}
					this._Theloaisach.Entity = value;
					if ((value != null))
					{
						value.Sach_Theloaisaches.Add(this);
						this._Matheloai = value.Matheloai;
					}
					else
					{
						this._Matheloai = default(Nullable<int>);
					}
					this.SendPropertyChanged("Theloaisach");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sach_Sach_Theloaisach", Storage="_Sach", ThisKey="Masach", OtherKey="Masach", IsForeignKey=true)]
		public Sach Sach
		{
			get
			{
				return this._Sach.Entity;
			}
			set
			{
				Sach previousValue = this._Sach.Entity;
				if (((previousValue != value) 
							|| (this._Sach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sach.Entity = null;
						previousValue.Sach_Theloaisaches.Remove(this);
					}
					this._Sach.Entity = value;
					if ((value != null))
					{
						value.Sach_Theloaisaches.Add(this);
						this._Masach = value.Masach;
					}
					else
					{
						this._Masach = default(Nullable<int>);
					}
					this.SendPropertyChanged("Sach");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thedocgia")]
	public partial class Thedocgia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Mathedocgia;
		
		private System.Nullable<System.DateTime> _Ngaycap;
		
		private System.Nullable<System.DateTime> _Ngayhethan;
		
		private System.Nullable<int> _Madocgia;
		
		private EntitySet<Phieumuonsach> _Phieumuonsaches;
		
		private EntityRef<Docgia> _Docgia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMathedocgiaChanging(int value);
    partial void OnMathedocgiaChanged();
    partial void OnNgaycapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaycapChanged();
    partial void OnNgayhethanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayhethanChanged();
    partial void OnMadocgiaChanging(System.Nullable<int> value);
    partial void OnMadocgiaChanged();
    #endregion
		
		public Thedocgia()
		{
			this._Phieumuonsaches = new EntitySet<Phieumuonsach>(new Action<Phieumuonsach>(this.attach_Phieumuonsaches), new Action<Phieumuonsach>(this.detach_Phieumuonsaches));
			this._Docgia = default(EntityRef<Docgia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mathedocgia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Mathedocgia
		{
			get
			{
				return this._Mathedocgia;
			}
			set
			{
				if ((this._Mathedocgia != value))
				{
					this.OnMathedocgiaChanging(value);
					this.SendPropertyChanging();
					this._Mathedocgia = value;
					this.SendPropertyChanged("Mathedocgia");
					this.OnMathedocgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaycap", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaycap
		{
			get
			{
				return this._Ngaycap;
			}
			set
			{
				if ((this._Ngaycap != value))
				{
					this.OnNgaycapChanging(value);
					this.SendPropertyChanging();
					this._Ngaycap = value;
					this.SendPropertyChanged("Ngaycap");
					this.OnNgaycapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayhethan", DbType="Date")]
		public System.Nullable<System.DateTime> Ngayhethan
		{
			get
			{
				return this._Ngayhethan;
			}
			set
			{
				if ((this._Ngayhethan != value))
				{
					this.OnNgayhethanChanging(value);
					this.SendPropertyChanging();
					this._Ngayhethan = value;
					this.SendPropertyChanged("Ngayhethan");
					this.OnNgayhethanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madocgia", DbType="Int")]
		public System.Nullable<int> Madocgia
		{
			get
			{
				return this._Madocgia;
			}
			set
			{
				if ((this._Madocgia != value))
				{
					if (this._Docgia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMadocgiaChanging(value);
					this.SendPropertyChanging();
					this._Madocgia = value;
					this.SendPropertyChanged("Madocgia");
					this.OnMadocgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thedocgia_Phieumuonsach", Storage="_Phieumuonsaches", ThisKey="Mathedocgia", OtherKey="Mathedocgia")]
		public EntitySet<Phieumuonsach> Phieumuonsaches
		{
			get
			{
				return this._Phieumuonsaches;
			}
			set
			{
				this._Phieumuonsaches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Docgia_Thedocgia", Storage="_Docgia", ThisKey="Madocgia", OtherKey="Madocgia", IsForeignKey=true)]
		public Docgia Docgia
		{
			get
			{
				return this._Docgia.Entity;
			}
			set
			{
				Docgia previousValue = this._Docgia.Entity;
				if (((previousValue != value) 
							|| (this._Docgia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Docgia.Entity = null;
						previousValue.Thedocgias.Remove(this);
					}
					this._Docgia.Entity = value;
					if ((value != null))
					{
						value.Thedocgias.Add(this);
						this._Madocgia = value.Madocgia;
					}
					else
					{
						this._Madocgia = default(Nullable<int>);
					}
					this.SendPropertyChanged("Docgia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phieumuonsaches(Phieumuonsach entity)
		{
			this.SendPropertyChanging();
			entity.Thedocgia = this;
		}
		
		private void detach_Phieumuonsaches(Phieumuonsach entity)
		{
			this.SendPropertyChanging();
			entity.Thedocgia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Docgia")]
	public partial class Docgia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Madocgia;
		
		private string _Tendocgia;
		
		private System.Nullable<int> _Namsinh;
		
		private System.Nullable<int> _Sodienthoai;
		
		private string _Gioitinh;
		
		private EntitySet<Thedocgia> _Thedocgias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMadocgiaChanging(int value);
    partial void OnMadocgiaChanged();
    partial void OnTendocgiaChanging(string value);
    partial void OnTendocgiaChanged();
    partial void OnNamsinhChanging(System.Nullable<int> value);
    partial void OnNamsinhChanged();
    partial void OnSodienthoaiChanging(System.Nullable<int> value);
    partial void OnSodienthoaiChanged();
    partial void OnGioitinhChanging(string value);
    partial void OnGioitinhChanged();
    #endregion
		
		public Docgia()
		{
			this._Thedocgias = new EntitySet<Thedocgia>(new Action<Thedocgia>(this.attach_Thedocgias), new Action<Thedocgia>(this.detach_Thedocgias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madocgia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Madocgia
		{
			get
			{
				return this._Madocgia;
			}
			set
			{
				if ((this._Madocgia != value))
				{
					this.OnMadocgiaChanging(value);
					this.SendPropertyChanging();
					this._Madocgia = value;
					this.SendPropertyChanged("Madocgia");
					this.OnMadocgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tendocgia", DbType="NVarChar(100)")]
		public string Tendocgia
		{
			get
			{
				return this._Tendocgia;
			}
			set
			{
				if ((this._Tendocgia != value))
				{
					this.OnTendocgiaChanging(value);
					this.SendPropertyChanging();
					this._Tendocgia = value;
					this.SendPropertyChanged("Tendocgia");
					this.OnTendocgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Namsinh", DbType="Int")]
		public System.Nullable<int> Namsinh
		{
			get
			{
				return this._Namsinh;
			}
			set
			{
				if ((this._Namsinh != value))
				{
					this.OnNamsinhChanging(value);
					this.SendPropertyChanging();
					this._Namsinh = value;
					this.SendPropertyChanged("Namsinh");
					this.OnNamsinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sodienthoai", DbType="Int")]
		public System.Nullable<int> Sodienthoai
		{
			get
			{
				return this._Sodienthoai;
			}
			set
			{
				if ((this._Sodienthoai != value))
				{
					this.OnSodienthoaiChanging(value);
					this.SendPropertyChanging();
					this._Sodienthoai = value;
					this.SendPropertyChanged("Sodienthoai");
					this.OnSodienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="NVarChar(5)")]
		public string Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Docgia_Thedocgia", Storage="_Thedocgias", ThisKey="Madocgia", OtherKey="Madocgia")]
		public EntitySet<Thedocgia> Thedocgias
		{
			get
			{
				return this._Thedocgias;
			}
			set
			{
				this._Thedocgias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thedocgias(Thedocgia entity)
		{
			this.SendPropertyChanging();
			entity.Docgia = this;
		}
		
		private void detach_Thedocgias(Thedocgia entity)
		{
			this.SendPropertyChanging();
			entity.Docgia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sach")]
	public partial class Sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Masach;
		
		private string _Tensach;
		
		private string _Nhaxuatban;
		
		private System.Nullable<int> _Giathue;
		
		private System.Nullable<int> _Namxuatban;
		
		private System.Nullable<int> _Soluong;
		
		private System.Nullable<int> _Soluongconlai;
		
		private EntitySet<Sach_Theloaisach> _Sach_Theloaisaches;
		
		private EntitySet<Phieumuonsach_sach> _Phieumuonsach_saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMasachChanging(int value);
    partial void OnMasachChanged();
    partial void OnTensachChanging(string value);
    partial void OnTensachChanged();
    partial void OnNhaxuatbanChanging(string value);
    partial void OnNhaxuatbanChanged();
    partial void OnGiathueChanging(System.Nullable<int> value);
    partial void OnGiathueChanged();
    partial void OnNamxuatbanChanging(System.Nullable<int> value);
    partial void OnNamxuatbanChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    partial void OnSoluongconlaiChanging(System.Nullable<int> value);
    partial void OnSoluongconlaiChanged();
    #endregion
		
		public Sach()
		{
			this._Sach_Theloaisaches = new EntitySet<Sach_Theloaisach>(new Action<Sach_Theloaisach>(this.attach_Sach_Theloaisaches), new Action<Sach_Theloaisach>(this.detach_Sach_Theloaisaches));
			this._Phieumuonsach_saches = new EntitySet<Phieumuonsach_sach>(new Action<Phieumuonsach_sach>(this.attach_Phieumuonsach_saches), new Action<Phieumuonsach_sach>(this.detach_Phieumuonsach_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Masach", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Masach
		{
			get
			{
				return this._Masach;
			}
			set
			{
				if ((this._Masach != value))
				{
					this.OnMasachChanging(value);
					this.SendPropertyChanging();
					this._Masach = value;
					this.SendPropertyChanged("Masach");
					this.OnMasachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tensach", DbType="NVarChar(100)")]
		public string Tensach
		{
			get
			{
				return this._Tensach;
			}
			set
			{
				if ((this._Tensach != value))
				{
					this.OnTensachChanging(value);
					this.SendPropertyChanging();
					this._Tensach = value;
					this.SendPropertyChanged("Tensach");
					this.OnTensachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhaxuatban", DbType="NVarChar(100)")]
		public string Nhaxuatban
		{
			get
			{
				return this._Nhaxuatban;
			}
			set
			{
				if ((this._Nhaxuatban != value))
				{
					this.OnNhaxuatbanChanging(value);
					this.SendPropertyChanging();
					this._Nhaxuatban = value;
					this.SendPropertyChanged("Nhaxuatban");
					this.OnNhaxuatbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giathue", DbType="Int")]
		public System.Nullable<int> Giathue
		{
			get
			{
				return this._Giathue;
			}
			set
			{
				if ((this._Giathue != value))
				{
					this.OnGiathueChanging(value);
					this.SendPropertyChanging();
					this._Giathue = value;
					this.SendPropertyChanged("Giathue");
					this.OnGiathueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Namxuatban", DbType="Int")]
		public System.Nullable<int> Namxuatban
		{
			get
			{
				return this._Namxuatban;
			}
			set
			{
				if ((this._Namxuatban != value))
				{
					this.OnNamxuatbanChanging(value);
					this.SendPropertyChanging();
					this._Namxuatban = value;
					this.SendPropertyChanged("Namxuatban");
					this.OnNamxuatbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluongconlai", DbType="Int")]
		public System.Nullable<int> Soluongconlai
		{
			get
			{
				return this._Soluongconlai;
			}
			set
			{
				if ((this._Soluongconlai != value))
				{
					this.OnSoluongconlaiChanging(value);
					this.SendPropertyChanging();
					this._Soluongconlai = value;
					this.SendPropertyChanged("Soluongconlai");
					this.OnSoluongconlaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sach_Sach_Theloaisach", Storage="_Sach_Theloaisaches", ThisKey="Masach", OtherKey="Masach")]
		public EntitySet<Sach_Theloaisach> Sach_Theloaisaches
		{
			get
			{
				return this._Sach_Theloaisaches;
			}
			set
			{
				this._Sach_Theloaisaches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sach_Phieumuonsach_sach", Storage="_Phieumuonsach_saches", ThisKey="Masach", OtherKey="Masach")]
		public EntitySet<Phieumuonsach_sach> Phieumuonsach_saches
		{
			get
			{
				return this._Phieumuonsach_saches;
			}
			set
			{
				this._Phieumuonsach_saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sach_Theloaisaches(Sach_Theloaisach entity)
		{
			this.SendPropertyChanging();
			entity.Sach = this;
		}
		
		private void detach_Sach_Theloaisaches(Sach_Theloaisach entity)
		{
			this.SendPropertyChanging();
			entity.Sach = null;
		}
		
		private void attach_Phieumuonsach_saches(Phieumuonsach_sach entity)
		{
			this.SendPropertyChanging();
			entity.Sach = this;
		}
		
		private void detach_Phieumuonsach_saches(Phieumuonsach_sach entity)
		{
			this.SendPropertyChanging();
			entity.Sach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phieumuonsach_sach")]
	public partial class Phieumuonsach_sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _Maphieumuon;
		
		private System.Nullable<int> _Masach;
		
		private int _Maphieumuonsach_sach;
		
		private EntityRef<Phieumuonsach> _Phieumuonsach;
		
		private EntityRef<Sach> _Sach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaphieumuonChanging(System.Nullable<int> value);
    partial void OnMaphieumuonChanged();
    partial void OnMasachChanging(System.Nullable<int> value);
    partial void OnMasachChanged();
    partial void OnMaphieumuonsach_sachChanging(int value);
    partial void OnMaphieumuonsach_sachChanged();
    #endregion
		
		public Phieumuonsach_sach()
		{
			this._Phieumuonsach = default(EntityRef<Phieumuonsach>);
			this._Sach = default(EntityRef<Sach>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maphieumuon", DbType="Int")]
		public System.Nullable<int> Maphieumuon
		{
			get
			{
				return this._Maphieumuon;
			}
			set
			{
				if ((this._Maphieumuon != value))
				{
					if (this._Phieumuonsach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaphieumuonChanging(value);
					this.SendPropertyChanging();
					this._Maphieumuon = value;
					this.SendPropertyChanged("Maphieumuon");
					this.OnMaphieumuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Masach", DbType="Int")]
		public System.Nullable<int> Masach
		{
			get
			{
				return this._Masach;
			}
			set
			{
				if ((this._Masach != value))
				{
					if (this._Sach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMasachChanging(value);
					this.SendPropertyChanging();
					this._Masach = value;
					this.SendPropertyChanged("Masach");
					this.OnMasachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maphieumuonsach_sach", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Maphieumuonsach_sach
		{
			get
			{
				return this._Maphieumuonsach_sach;
			}
			set
			{
				if ((this._Maphieumuonsach_sach != value))
				{
					this.OnMaphieumuonsach_sachChanging(value);
					this.SendPropertyChanging();
					this._Maphieumuonsach_sach = value;
					this.SendPropertyChanged("Maphieumuonsach_sach");
					this.OnMaphieumuonsach_sachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phieumuonsach_Phieumuonsach_sach", Storage="_Phieumuonsach", ThisKey="Maphieumuon", OtherKey="Maphieumuon", IsForeignKey=true)]
		public Phieumuonsach Phieumuonsach
		{
			get
			{
				return this._Phieumuonsach.Entity;
			}
			set
			{
				Phieumuonsach previousValue = this._Phieumuonsach.Entity;
				if (((previousValue != value) 
							|| (this._Phieumuonsach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phieumuonsach.Entity = null;
						previousValue.Phieumuonsach_saches.Remove(this);
					}
					this._Phieumuonsach.Entity = value;
					if ((value != null))
					{
						value.Phieumuonsach_saches.Add(this);
						this._Maphieumuon = value.Maphieumuon;
					}
					else
					{
						this._Maphieumuon = default(Nullable<int>);
					}
					this.SendPropertyChanged("Phieumuonsach");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sach_Phieumuonsach_sach", Storage="_Sach", ThisKey="Masach", OtherKey="Masach", IsForeignKey=true)]
		public Sach Sach
		{
			get
			{
				return this._Sach.Entity;
			}
			set
			{
				Sach previousValue = this._Sach.Entity;
				if (((previousValue != value) 
							|| (this._Sach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sach.Entity = null;
						previousValue.Phieumuonsach_saches.Remove(this);
					}
					this._Sach.Entity = value;
					if ((value != null))
					{
						value.Phieumuonsach_saches.Add(this);
						this._Masach = value.Masach;
					}
					else
					{
						this._Masach = default(Nullable<int>);
					}
					this.SendPropertyChanged("Sach");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nhanvien")]
	public partial class Nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Manhanvien;
		
		private string _Tennhanvien;
		
		private System.Nullable<int> _Sdtnhanvien;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnManhanvienChanging(int value);
    partial void OnManhanvienChanged();
    partial void OnTennhanvienChanging(string value);
    partial void OnTennhanvienChanged();
    partial void OnSdtnhanvienChanging(System.Nullable<int> value);
    partial void OnSdtnhanvienChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Nhanvien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhanvien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Manhanvien
		{
			get
			{
				return this._Manhanvien;
			}
			set
			{
				if ((this._Manhanvien != value))
				{
					this.OnManhanvienChanging(value);
					this.SendPropertyChanging();
					this._Manhanvien = value;
					this.SendPropertyChanged("Manhanvien");
					this.OnManhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tennhanvien", DbType="NVarChar(100)")]
		public string Tennhanvien
		{
			get
			{
				return this._Tennhanvien;
			}
			set
			{
				if ((this._Tennhanvien != value))
				{
					this.OnTennhanvienChanging(value);
					this.SendPropertyChanging();
					this._Tennhanvien = value;
					this.SendPropertyChanged("Tennhanvien");
					this.OnTennhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdtnhanvien", DbType="Int")]
		public System.Nullable<int> Sdtnhanvien
		{
			get
			{
				return this._Sdtnhanvien;
			}
			set
			{
				if ((this._Sdtnhanvien != value))
				{
					this.OnSdtnhanvienChanging(value);
					this.SendPropertyChanging();
					this._Sdtnhanvien = value;
					this.SendPropertyChanged("Sdtnhanvien");
					this.OnSdtnhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Taikhoan")]
	public partial class Taikhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Tendangnhap;
		
		private string _Matkhau;
		
		private System.Nullable<int> _Quyen;
		
		private System.Nullable<int> _Manhanvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTendangnhapChanging(string value);
    partial void OnTendangnhapChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnQuyenChanging(System.Nullable<int> value);
    partial void OnQuyenChanged();
    partial void OnManhanvienChanging(System.Nullable<int> value);
    partial void OnManhanvienChanged();
    #endregion
		
		public Taikhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tendangnhap", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Tendangnhap
		{
			get
			{
				return this._Tendangnhap;
			}
			set
			{
				if ((this._Tendangnhap != value))
				{
					this.OnTendangnhapChanging(value);
					this.SendPropertyChanging();
					this._Tendangnhap = value;
					this.SendPropertyChanged("Tendangnhap");
					this.OnTendangnhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="VarChar(100)")]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="Int")]
		public System.Nullable<int> Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhanvien", DbType="Int")]
		public System.Nullable<int> Manhanvien
		{
			get
			{
				return this._Manhanvien;
			}
			set
			{
				if ((this._Manhanvien != value))
				{
					this.OnManhanvienChanging(value);
					this.SendPropertyChanging();
					this._Manhanvien = value;
					this.SendPropertyChanged("Manhanvien");
					this.OnManhanvienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
